service:
  name: sql-migration
  region: eu-west-1

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  migration:
    handler: src/triggers/migrate.migrate
    timeout: 200
    memorySize: 512
    vpc:
      securityGroupIds:
      - <security group with access to RDS>
      subnetIds:
      - <subnet which has access to the VPC>
    environment:
      USERNAME: ${ssm:QS_RDS_USERNAME}
      ENDPOINT: ${ssm:QS_RDS_ENDPOINT}
      DATABASE: ${ssm:QS_RDS_DATABASE}
      PASSWORD: ${ssm:QS_RDS_PASSWORD}
      PORT: ${ssm:QS_RDS_PORT}